### ISSUE TITLE
YCM left uncompiled. Causes issues.

### ISSUE THREAD

**Issue by reilg** [mxaddict/dotfiles#1]
Whenever I startup `vim` I get this error:
````
ycm_client_support.[so|pyd|dll] and ycm_core.[so|pyd|dll] not detected; 
you need to compile YCM before using it. Read the docs!
````

Re-running dotfile installer does not fix the issue.
Manually running `vim +PlugUpgrade +PlugClean! +PlugUpdate +qall` or any variation of Vim plugin update command doesn't fix it. 

As a side-effect of having error prompts when vim is run, running `tmux` shows the error: `/home/Bianca/.tmuxline.conf: No such file or directory`.

This was done on a Windows 7 machine. Using [**babun**](babun.github.io).

*Note:*
Manually running `./install.sh --clang-completer` from `~/.vim/plugged/YouCompleteMe` doesn't seem to do anything.

**Comment by mxaddict** [comment]
@reilg, seems like an issue for YCM, not my dotfiles :)
